---
deployment:
  tasks:
    # Set deployment path (adjust username if needed)
    - export DEPLOYPATH=/home/$$USER/public_html/

    # Copy all files from repository root to public_html
    # Note: This assumes your repository root contains the public_html files
    - /bin/cp -Rf public_html/* $$DEPLOYPATH

    # Set proper file permissions
    - /bin/chmod -R 755 $$DEPLOYPATH
    - /bin/find $$DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $$DEPLOYPATH -type d -exec chmod 755 {} \;

    # Preserve .htaccess if it exists
    - if [ -f public_html/.htaccess ]; then /bin/cp -f public_html/.htaccess $$DEPLOYPATH; fi
